Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder ".", "/var/www/html"

  config.vm.provider "virtualbox" do |vb| 
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
	sudo apt-get update
	sudo apt-get -y install apache2
	
	sudo apt-get install ufw
	sudo ufw allow 80/tcp
	sudo ufw allow 22/tcp
	sudo ufw allow out 22/tcp
	sudo ufw enable
	
	sudo apt-get -y install openssh-server
	
	sudo apt-get -y install libapache2-mod-proxy-html
	sudo apt-get -y install libxml12-dev
	
	sudo a2enmod proxy
	sudo a2enmod proxy_html
	sudo a2enmod proxy_http
	sudo service apache2 restart
	
	sudo groupadd users
		sudo useradd test -g admin -m -s /bin/bash
		sudo chpasswd <<<test:1234
	exit  
  SHELL

end