Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder ".", "/var/www/html"

  config.vm.provider "virtualbox" do |vb| 
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
	sudo apt-get update
	sudo apt-get -y install apache2
	
	sudo apt-get install ufw
	sudo ufw allow 80/tcp
	sudo ufw allow 22/tcp
	sudo ufw allow out 22/tcp
	sudo ufw enable
	
	sudo apt-get -y install openssh-server
	
	sudo apt-get -y install libapache2-mod-proxy-html
	sudo apt-get -y install libxml12-dev
	
	sudo a2enmod proxy
	sudo a2enmod proxy_html
	sudo a2enmod proxy_http
  sudo service apache2 restart
  
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
  sudo apt-get update
  apt-cache policy docker-ce
  sudo apt-get install -y docker-ce
  sudo systemctl status docker
  sudo apt-get install curl
  udo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
	
	sudo groupadd users
		sudo useradd test -g admin -m -s /bin/bash
		sudo chpasswd <<<test:1234
	exit  
  SHELL

end